INSERT INTO TB_CATEGORY (NAME ,created_At) VALUES ('Books',now());
INSERT INTO TB_CATEGORY (NAME ,created_At) VALUES ('Eletronics',now());
INSERT INTO TB_CATEGORY (NAME,created_At) VALUES ('Computers',now());
INSERT INTO TB_CATEGORY (NAME ,created_At) VALUES ('Books',now());
INSERT INTO TB_CATEGORY (NAME ,created_At) VALUES ('Eletronics',now());
INSERT INTO TB_CATEGORY (NAME,created_At) VALUES ('Computers',now());
INSERT INTO TB_CATEGORY (NAME ,created_At) VALUES ('Books',now());
INSERT INTO TB_CATEGORY (NAME ,created_At) VALUES ('Eletronics',now());
INSERT INTO TB_CATEGORY (NAME,created_At) VALUES ('Computers',now());
INSERT INTO TB_CATEGORY (NAME ,created_At) VALUES ('Books',now());
INSERT INTO TB_CATEGORY (NAME ,created_At) VALUES ('Eletronics',now());
INSERT INTO TB_CATEGORY (NAME,created_At) VALUES ('Computers',now());
INSERT INTO TB_CATEGORY (NAME ,created_At) VALUES ('Books',now());
INSERT INTO TB_CATEGORY (NAME ,created_At) VALUES ('Eletronics',now());
INSERT INTO TB_CATEGORY (NAME,created_At) VALUES ('Computers',now());
INSERT INTO TB_CATEGORY (NAME ,created_At) VALUES ('Books',now());
INSERT INTO TB_CATEGORY (NAME ,created_At) VALUES ('Eletronics',now());
INSERT INTO TB_CATEGORY (NAME,created_At) VALUES ('Computers',now());
INSERT INTO TB_CATEGORY (NAME ,created_At) VALUES ('Books',now());
INSERT INTO TB_CATEGORY (NAME ,created_At) VALUES ('Eletronics',now());
INSERT INTO TB_CATEGORY (NAME,created_At) VALUES ('Computers',now());
INSERT INTO TB_CATEGORY (NAME ,created_At) VALUES ('Books',now());
INSERT INTO TB_CATEGORY (NAME ,created_At) VALUES ('Eletronics',now());
INSERT INTO TB_CATEGORY (NAME,created_At) VALUES ('Computers',now());
INSERT INTO TB_CATEGORY (NAME ,created_At) VALUES ('Books',now());
INSERT INTO TB_CATEGORY (NAME ,created_At) VALUES ('Eletronics',now());
INSERT INTO TB_CATEGORY (NAME,created_At) VALUES ('Computers',now());
INSERT INTO TB_CATEGORY (NAME ,created_At) VALUES ('Books',now());
INSERT INTO TB_CATEGORY (NAME ,created_At) VALUES ('Eletronics',now());
INSERT INTO TB_CATEGORY (NAME,created_At) VALUES ('Computers',now());
INSERT INTO TB_CATEGORY (NAME ,created_At) VALUES ('Books',now());
INSERT INTO TB_CATEGORY (NAME ,created_At) VALUES ('Eletronics',now());
INSERT INTO TB_CATEGORY (NAME,created_At) VALUES ('Computers',now());
INSERT INTO TB_CATEGORY (NAME ,created_At) VALUES ('Books',now());
INSERT INTO TB_CATEGORY (NAME ,created_At) VALUES ('Eletronics',now());
INSERT INTO TB_CATEGORY (NAME,created_At) VALUES ('Computers',now());
